In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df_fertility= pd.read_excel(r"C:\Users\nxg11006\OneDrive - NXP\Desktop\Datasets\Fertility rate, total (births per woman)\API_SP.DYN.TFRT.IN_DS2_en_excel_v2_2276.xls", engine='xlrd')
df_fertility

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69
0,Last Updated Date,2026-07-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.00000,1961.000000,1962.000000,1963.000000,1964.00000,1965.000000,...,2016.000000,2017.000000,2018.000000,2019.000000,2020.000000,2021.000000,2022.00000,2023.000000,2024.000000,2025.0
3,Aruba,ABW,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,4.56700,4.422000,4.262000,4.107000,3.94000,3.797000,...,1.848000,1.785000,1.732000,1.701000,1.662000,1.631000,1.61500,1.602000,1.606000,NaN
4,Africa Eastern and Southern,AFE,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.65031,6.667308,6.688246,6.709226,6.72493,6.737459,...,4.615756,4.569915,4.521454,4.471351,4.412999,4.350691,4.28708,4.223861,4.164044,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.35900,6.314000,6.244000,6.176000,6.11200,6.035000,...,1.641000,1.618000,1.581000,1.575000,1.567000,1.561000,1.55500,1.545000,1.538000,NaN
264,"Yemen, Rep.",YEM,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,7.98800,8.000000,8.010000,8.028000,8.07100,8.101000,...,4.613000,4.610000,4.607000,4.603000,4.600000,4.597000,4.59300,4.590000,4.499000,NaN
265,South Africa,ZAF,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.10500,6.080000,6.046000,6.012000,5.95500,5.892000,...,2.261000,2.283000,2.270000,2.264000,2.257000,2.248000,2.22700,2.216000,2.205000,NaN
266,Zambia,ZMB,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.94700,6.982000,7.012000,7.060000,7.08500,7.116000,...,4.669000,4.567000,4.492000,4.418000,4.323000,4.246000,4.17500,4.101000,4.036000,NaN
267,Zimbabwe,ZWE,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,7.19500,7.212000,7.231000,7.230000,7.23000,7.231000,...,3.828000,3.768000,3.744000,3.748000,3.754000,3.765000,3.76700,3.724000,3.674000,NaN

In [3]:
df_fertility.shape

(268, 70)

Dropping first 2 rows - metadata

In [4]:
df_fertility.iloc[2].tolist()[:4]

['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code']

In [ ]:
temp_list1 = df_fertility.iloc[2].tolist()[:4] #integers
temp_list2 = df_fertility.iloc[2].tolist()[4:] #strings
temp_list2 = list(map(int, temp_list2))
temp_list1.extend(temp_list2) #creating column headers

In [ ]:
df_fertility.columns = temp_list1 #resetting default columns

In [7]:
df_fertility = df_fertility.iloc[3:].reset_index(drop=True)
df_fertility

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Aruba,ABW,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,4.567000,4.422000,4.262000,4.107000,3.940000,3.797000,...,1.848000,1.785000,1.732000,1.701000,1.662000,1.631000,1.615000,1.602000,1.606000,NaN
1,Africa Eastern and Southern,AFE,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.650310,6.667308,6.688246,6.709226,6.724930,6.737459,...,4.615756,4.569915,4.521454,4.471351,4.412999,4.350691,4.287080,4.223861,4.164044,NaN
2,Afghanistan,AFG,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,7.282000,7.284000,7.292000,7.302000,7.304000,7.305000,...,5.542000,5.433000,5.327000,5.238000,5.145000,5.039000,4.932000,4.840000,4.761000,NaN
3,Africa Western and Central,AFW,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.468882,6.478345,6.492276,6.500230,6.516724,6.532705,...,5.229433,5.099256,4.962885,4.829455,4.707739,4.638139,4.563817,4.498196,4.416450,NaN
4,Angola,AGO,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.708000,6.790000,6.872000,6.954000,7.036000,7.116000,...,5.686000,5.600000,5.519000,5.442000,5.371000,5.304000,5.209000,5.124000,5.048000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,Kosovo,XKX,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.359000,6.314000,6.244000,6.176000,6.112000,6.035000,...,1.641000,1.618000,1.581000,1.575000,1.567000,1.561000,1.555000,1.545000,1.538000,NaN
261,"Yemen, Rep.",YEM,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,7.988000,8.000000,8.010000,8.028000,8.071000,8.101000,...,4.613000,4.610000,4.607000,4.603000,4.600000,4.597000,4.593000,4.590000,4.499000,NaN
262,South Africa,ZAF,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.105000,6.080000,6.046000,6.012000,5.955000,5.892000,...,2.261000,2.283000,2.270000,2.264000,2.257000,2.248000,2.227000,2.216000,2.205000,NaN
263,Zambia,ZMB,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.947000,6.982000,7.012000,7.060000,7.085000,7.116000,...,4.669000,4.567000,4.492000,4.418000,4.323000,4.246000,4.175000,4.101000,4.036000,NaN
264,Zimbabwe,ZWE,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,7.195000,7.212000,7.231000,7.230000,7.230000,7.231000,...,3.828000,3.768000,3.744000,3.748000,3.754000,3.765000,3.767000,3.724000,3.674000,NaN

Checking columns with all null values and dropping them.

In [9]:
for i in df_fertility.columns:
    if df_fertility[i].isna().all():
        df_fertility.drop(columns=i, inplace=True)

df_fertility

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Aruba,ABW,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,4.567000,4.422000,4.262000,4.107000,3.940000,3.797000,...,1.899000,1.848000,1.785000,1.732000,1.701000,1.662000,1.631000,1.615000,1.602000,1.606000
1,Africa Eastern and Southern,AFE,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.650310,6.667308,6.688246,6.709226,6.724930,6.737459,...,4.676523,4.615756,4.569915,4.521454,4.471351,4.412999,4.350691,4.287080,4.223861,4.164044
2,Afghanistan,AFG,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,7.282000,7.284000,7.292000,7.302000,7.304000,7.305000,...,5.652000,5.542000,5.433000,5.327000,5.238000,5.145000,5.039000,4.932000,4.840000,4.761000
3,Africa Western and Central,AFW,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.468882,6.478345,6.492276,6.500230,6.516724,6.532705,...,5.347161,5.229433,5.099256,4.962885,4.829455,4.707739,4.638139,4.563817,4.498196,4.416450
4,Angola,AGO,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.708000,6.790000,6.872000,6.954000,7.036000,7.116000,...,5.774000,5.686000,5.600000,5.519000,5.442000,5.371000,5.304000,5.209000,5.124000,5.048000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,Kosovo,XKX,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.359000,6.314000,6.244000,6.176000,6.112000,6.035000,...,1.763000,1.641000,1.618000,1.581000,1.575000,1.567000,1.561000,1.555000,1.545000,1.538000
261,"Yemen, Rep.",YEM,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,7.988000,8.000000,8.010000,8.028000,8.071000,8.101000,...,4.617000,4.613000,4.610000,4.607000,4.603000,4.600000,4.597000,4.593000,4.590000,4.499000
262,South Africa,ZAF,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.105000,6.080000,6.046000,6.012000,5.955000,5.892000,...,2.359000,2.261000,2.283000,2.270000,2.264000,2.257000,2.248000,2.227000,2.216000,2.205000
263,Zambia,ZMB,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.947000,6.982000,7.012000,7.060000,7.085000,7.116000,...,4.775000,4.669000,4.567000,4.492000,4.418000,4.323000,4.246000,4.175000,4.101000,4.036000
264,Zimbabwe,ZWE,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,7.195000,7.212000,7.231000,7.230000,7.230000,7.231000,...,3.911000,3.828000,3.768000,3.744000,3.748000,3.754000,3.765000,3.767000,3.724000,3.674000

Combining income data with main df

In [10]:
df_income = pd.read_excel(r"C:\Users\nxg11006\OneDrive - NXP\Desktop\Datasets\Fertility rate, total (births per woman)\API_SP.DYN.TFRT.IN_DS2_en_excel_v2_2276.xls", sheet_name='Metadata - Countries', engine='xlrd')
df_income

,Country Code,Region,IncomeGroup,SpecialNotes,TableName
0,ABW,Latin America & Caribbean,High income,NaN,Aruba
1,AFE,NaN,NaN,"26 countries, stretching from the Red Sea in t...",Africa Eastern and Southern
2,AFG,Middle East & North Africa,Low income,The reporting period for national accounts dat...,Afghanistan
3,AFW,NaN,NaN,"22 countries, stretching from the westernmost ...",Africa Western and Central
4,AGO,Sub-Saharan Africa,Lower middle income,The World Bank systematically assesses the app...,Angola
...,...,...,...,...,...
259,XKX,Europe & Central Asia,Upper middle income,NaN,Kosovo
260,YEM,Middle East & North Africa,Low income,The World Bank systematically assesses the app...,"Yemen, Rep."
261,ZAF,Sub-Saharan Africa,Upper middle income,Fiscal year end: March 31; reporting period fo...,South Africa
262,ZMB,Sub-Saharan Africa,Lower middle income,National accounts data were rebased to reflect...,Zambia
263,ZWE,Sub-Saharan Africa,Lower middle income,National Accounts data are reported in Zimbabw...,Zimbabwe

In [ ]:
len(df_income['Country Code'].unique())  #checking if there are redundant values in the columns

264

In [12]:
df_income.drop(columns=['Country Code','SpecialNotes','TableName'], inplace=True)

In [13]:
df_income

                         Region          IncomeGroup
0     Latin America & Caribbean          High income
1                           NaN                  NaN
2    Middle East & North Africa           Low income
3                           NaN                  NaN
4            Sub-Saharan Africa  Lower middle income
..                          ...                  ...
259       Europe & Central Asia  Upper middle income
260  Middle East & North Africa           Low income
261          Sub-Saharan Africa  Upper middle income
262          Sub-Saharan Africa  Lower middle income
263          Sub-Saharan Africa  Lower middle income

[264 rows x 2 columns]

Filling missing values with custom text for better interpretation in 'IncomeGroup' and 'Region' columns.

In [14]:
df_fertility = pd.concat([df_fertility, df_income], axis=1)
df_fertility['IncomeGroup'] = df_fertility['IncomeGroup'].fillna('Income Unavailable')
df_fertility['Region'] = df_fertility['Region'].fillna('Region Unavailable')
df_fertility

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,Region,IncomeGroup
0,Aruba,ABW,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,4.567000,4.422000,4.262000,4.107000,3.940000,3.797000,...,1.785000,1.732000,1.701000,1.662000,1.631000,1.615000,1.602000,1.606000,Latin America & Caribbean,High income
1,Africa Eastern and Southern,AFE,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.650310,6.667308,6.688246,6.709226,6.724930,6.737459,...,4.569915,4.521454,4.471351,4.412999,4.350691,4.287080,4.223861,4.164044,Region Unavailable,Income Unavailable
2,Afghanistan,AFG,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,7.282000,7.284000,7.292000,7.302000,7.304000,7.305000,...,5.433000,5.327000,5.238000,5.145000,5.039000,4.932000,4.840000,4.761000,Middle East & North Africa,Low income
3,Africa Western and Central,AFW,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.468882,6.478345,6.492276,6.500230,6.516724,6.532705,...,5.099256,4.962885,4.829455,4.707739,4.638139,4.563817,4.498196,4.416450,Region Unavailable,Income Unavailable
4,Angola,AGO,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.708000,6.790000,6.872000,6.954000,7.036000,7.116000,...,5.600000,5.519000,5.442000,5.371000,5.304000,5.209000,5.124000,5.048000,Sub-Saharan Africa,Lower middle income
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,Kosovo,XKX,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.359000,6.314000,6.244000,6.176000,6.112000,6.035000,...,1.618000,1.581000,1.575000,1.567000,1.561000,1.555000,1.545000,1.538000,Middle East & North Africa,Low income
261,"Yemen, Rep.",YEM,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,7.988000,8.000000,8.010000,8.028000,8.071000,8.101000,...,4.610000,4.607000,4.603000,4.600000,4.597000,4.593000,4.590000,4.499000,Sub-Saharan Africa,Upper middle income
262,South Africa,ZAF,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.105000,6.080000,6.046000,6.012000,5.955000,5.892000,...,2.283000,2.270000,2.264000,2.257000,2.248000,2.227000,2.216000,2.205000,Sub-Saharan Africa,Lower middle income
263,Zambia,ZMB,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.947000,6.982000,7.012000,7.060000,7.085000,7.116000,...,4.567000,4.492000,4.418000,4.323000,4.246000,4.175000,4.101000,4.036000,Sub-Saharan Africa,Lower middle income
264,Zimbabwe,ZWE,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,7.195000,7.212000,7.231000,7.230000,7.230000,7.231000,...,3.768000,3.744000,3.748000,3.754000,3.765000,3.767000,3.724000,3.674000,Region Unavailable,Income Unavailable

In [ ]:
df_fertility.to_csv('df_fertility.csv', index=False) #saving file for dashboard usage.